version = "1.0"

[metadata]
author_name = "Ikenna Ifekaonwu"
author_email = "ifekaonwuikenna@gmail.com"
difficulty = "unknown"
category = "software-engineering"
tags = [ "file-operations", "python", "csv"]
expert_time_estimate_min = 60
junior_time_estimate_min = 120

[verifier]
timeout_sec = 900.0

[agent]
timeout_sec = 900.0

[task]
id = "csv-ingest-task" 
name = "CSV Ingestion Task"
version = "1.0.0"

[environment]
environment_name = "pythoncsv"
type = "docker"
dockerfile = "environment/Dockerfile"
docker_image = "python-csv-ingest"
