version = "1.0"

[metadata]
author_name = "Ikenna Ifekaonwu"
author_email = "ifekaonwuikenna@gmail.com"
difficulty = "unknown"
category = "software-engineering"
tags = [ "file-operations", "python", "csv"]
expert_time_estimate_min = 60
junior_time_estimate_min = 120

[verifier]
timeout_sec = 900.0

[agent]
timeout_sec = 900.0

[environment]
build_timeout_sec = 600.0
docker_image = "pythoncsvingest"
cpus = 1
memory_mb = 2048
storage_mb = 10240
