version: '3.8'

services:
  python-csv-ingest:
<<<<<<< Updated upstream
    image: ${MAIN_IMAGE_NAME}
=======
    image: ${MAIN_IMAGE_NAME:-python-csv-ingest}
>>>>>>> Stashed changes
    build:
      context: ..
      dockerfile: environment/Dockerfile
    container_name: python-csv
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    command: bash